services:
  web:
    image: nginx:alpine
    container_name: web_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: ./php
    container_name: php_fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: practica1
      MYSQL_USER: maria
      MYSQL_PASSWORD: medac26
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: